version: "3.2"

services:
  app:
    build: .
    image: mazzolino/swarmdns
    ports:
      - 53:53/udp
    command: --log
    # in 17.06
    #network_mode: host
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role == manager]
