FROM golang:alpine
EXPOSE 53/udp

WORKDIR /go/src/github.com/djmaze/wilddns/
COPY . .

RUN apk add --update --no-cache git \
 && go get ... \
 && go build \
 && apk del git pcre expat libcurl libssh2 \
 && rm -rf /go/pkg /go/src /var/cache/apk/*

ENTRYPOINT ["wilddns"]
